// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Monopoly.DataAccess.Postgres;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Monopoly.DataAccess.Postgres.Migrations
{
    [DbContext(typeof(MonopolyDbContext))]
    [Migration("20260126003016_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Monopoly.Core.Models.Abstractions.Classes.Cell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<string>("CellType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<bool>("Special")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Cells");

                    b.HasDiscriminator<string>("CellType").HasValue("Cell");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Monopoly.Core.Models.AccountModels.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Monopoly.Core.Models.GameModels.Dice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CountOfDubles")
                        .HasColumnType("integer");

                    b.Property<int>("Dice1")
                        .HasColumnType("integer");

                    b.Property<int>("Dice2")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Dices");
                });

            modelBuilder.Entity("Monopoly.Core.Models.GameModels.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Monopoly.Core.Models.GameModels.GameBoard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("Monopoly.Core.Models.GameModels.Monopoly", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMonopoly")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Monopolies");
                });

            modelBuilder.Entity("Monopoly.Core.Models.GameModels.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("Balance")
                        .HasColumnType("integer");

                    b.Property<int>("CantAction")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("InGame")
                        .HasColumnType("boolean");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPrisoner")
                        .HasColumnType("boolean");

                    b.Property<int>("Location")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReverseMove")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("GameId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Monopoly.Core.Models.GameModels.TurnState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanBuyCell")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanLevelUpCell")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanRollDices")
                        .HasColumnType("boolean");

                    b.Property<int>("CurrentPlayerIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("NeedPay")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("TurnStates");
                });

            modelBuilder.Entity("Monopoly.Core.Models.RoomModels.PlayerInRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("RoomId");

                    b.ToTable("PlayersInRooms");
                });

            modelBuilder.Entity("Monopoly.Core.Models.RoomModels.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("InGame")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxNumberOfPlayers")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Monopoly.Core.Models.GameModels.Cells.AmbulanceCell", b =>
                {
                    b.HasBaseType("Monopoly.Core.Models.Abstractions.Classes.Cell");

                    b.HasDiscriminator().HasValue("Ambulance");
                });

            modelBuilder.Entity("Monopoly.Core.Models.GameModels.Cells.CasinoCell", b =>
                {
                    b.HasBaseType("Monopoly.Core.Models.Abstractions.Classes.Cell");

                    b.HasDiscriminator().HasValue("Casino");
                });

            modelBuilder.Entity("Monopoly.Core.Models.GameModels.Cells.CompanyCell", b =>
                {
                    b.HasBaseType("Monopoly.Core.Models.Abstractions.Classes.Cell");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid>("MonopolyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("Rent")
                        .HasColumnType("integer");

                    b.HasIndex("MonopolyId");

                    b.HasIndex("OwnerId");

                    b.HasDiscriminator().HasValue("CompanyCell");
                });

            modelBuilder.Entity("Monopoly.Core.Models.GameModels.Cells.LosingMoneyCell", b =>
                {
                    b.HasBaseType("Monopoly.Core.Models.Abstractions.Classes.Cell");

                    b.Property<int>("Rent")
                        .HasColumnType("integer");

                    b.ToTable("Cells", t =>
                        {
                            t.Property("Rent")
                                .HasColumnName("LosingMoneyCell_Rent");
                        });

                    b.HasDiscriminator().HasValue("LosingMoney");
                });

            modelBuilder.Entity("Monopoly.Core.Models.GameModels.Cells.PrisonCell", b =>
                {
                    b.HasBaseType("Monopoly.Core.Models.Abstractions.Classes.Cell");

                    b.HasDiscriminator().HasValue("Prison");
                });

            modelBuilder.Entity("Monopoly.Core.Models.GameModels.Cells.ReceiveMoneyCell", b =>
                {
                    b.HasBaseType("Monopoly.Core.Models.Abstractions.Classes.Cell");

                    b.HasDiscriminator().HasValue("ReceiveMoney");
                });

            modelBuilder.Entity("Monopoly.Core.Models.GameModels.Cells.RestCell", b =>
                {
                    b.HasBaseType("Monopoly.Core.Models.Abstractions.Classes.Cell");

                    b.HasDiscriminator().HasValue("Rest");
                });

            modelBuilder.Entity("Monopoly.Core.Models.GameModels.Cells.ReverceCell", b =>
                {
                    b.HasBaseType("Monopoly.Core.Models.Abstractions.Classes.Cell");

                    b.HasDiscriminator().HasValue("Reverce");
                });

            modelBuilder.Entity("Monopoly.Core.Models.GameModels.Cells.StartCell", b =>
                {
                    b.HasBaseType("Monopoly.Core.Models.Abstractions.Classes.Cell");

                    b.HasDiscriminator().HasValue("Start");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Abstractions.Classes.Cell", b =>
                {
                    b.HasOne("Monopoly.Core.Models.GameModels.GameBoard", "Board")
                        .WithMany("Cells")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("Monopoly.Core.Models.GameModels.Dice", b =>
                {
                    b.HasOne("Monopoly.Core.Models.GameModels.Player", "Player")
                        .WithOne("Dices")
                        .HasForeignKey("Monopoly.Core.Models.GameModels.Dice", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Monopoly.Core.Models.GameModels.Game", b =>
                {
                    b.HasOne("Monopoly.Core.Models.RoomModels.Room", "Room")
                        .WithOne("Game")
                        .HasForeignKey("Monopoly.Core.Models.GameModels.Game", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Monopoly.Core.Models.GameModels.GameBoard", b =>
                {
                    b.HasOne("Monopoly.Core.Models.GameModels.Game", "Game")
                        .WithOne("Board")
                        .HasForeignKey("Monopoly.Core.Models.GameModels.GameBoard", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Monopoly.Core.Models.GameModels.Monopoly", b =>
                {
                    b.HasOne("Monopoly.Core.Models.GameModels.GameBoard", "Board")
                        .WithMany("Monopolies")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("Monopoly.Core.Models.GameModels.Player", b =>
                {
                    b.HasOne("Monopoly.Core.Models.AccountModels.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Monopoly.Core.Models.GameModels.Game", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Monopoly.Core.Models.GameModels.TurnState", b =>
                {
                    b.HasOne("Monopoly.Core.Models.GameModels.Game", "Game")
                        .WithOne("TurnState")
                        .HasForeignKey("Monopoly.Core.Models.GameModels.TurnState", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Monopoly.Core.Models.RoomModels.PlayerInRoom", b =>
                {
                    b.HasOne("Monopoly.Core.Models.AccountModels.Account", "Account")
                        .WithOne()
                        .HasForeignKey("Monopoly.Core.Models.RoomModels.PlayerInRoom", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Monopoly.Core.Models.RoomModels.Room", "Room")
                        .WithMany("Players")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Monopoly.Core.Models.GameModels.Cells.CompanyCell", b =>
                {
                    b.HasOne("Monopoly.Core.Models.GameModels.Monopoly", "Monopoly")
                        .WithMany("Cells")
                        .HasForeignKey("MonopolyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Monopoly.Core.Models.GameModels.Player", "Owner")
                        .WithMany("OwnedCells")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Monopoly");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Monopoly.Core.Models.GameModels.Game", b =>
                {
                    b.Navigation("Board")
                        .IsRequired();

                    b.Navigation("Players");

                    b.Navigation("TurnState")
                        .IsRequired();
                });

            modelBuilder.Entity("Monopoly.Core.Models.GameModels.GameBoard", b =>
                {
                    b.Navigation("Cells");

                    b.Navigation("Monopolies");
                });

            modelBuilder.Entity("Monopoly.Core.Models.GameModels.Monopoly", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("Monopoly.Core.Models.GameModels.Player", b =>
                {
                    b.Navigation("Dices")
                        .IsRequired();

                    b.Navigation("OwnedCells");
                });

            modelBuilder.Entity("Monopoly.Core.Models.RoomModels.Room", b =>
                {
                    b.Navigation("Game");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
