// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Monopoly.DataAccess.Postgres;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Monopoly.DataAccess.Postgres.Migrations
{
    [DbContext(typeof(MonopolyDbContext))]
    [Migration("20260609173749_AddTradingSystem")]
    partial class AddTradingSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Monopoly.Core.Models.Abstractions.Classes.Cell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<string>("CellType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<bool>("Special")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Cells");

                    b.HasDiscriminator<string>("CellType").HasValue("Cell");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Monopoly.Core.Models.Account.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.Dice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CountOfDubles")
                        .HasColumnType("integer");

                    b.Property<int>("Dice1")
                        .HasColumnType("integer");

                    b.Property<int>("Dice2")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Dices");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.GameBoard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.Monopoly", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMonopoly")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Monopolies");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.OfferSystem.Proposition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<List<int>>("CellNumbers")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("Money")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Propositions");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.OfferSystem.TradeOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OffereeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OffereePropositionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OffererId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OffererPropositionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.HasIndex("OffereeId");

                    b.HasIndex("OffereePropositionId")
                        .IsUnique();

                    b.HasIndex("OffererId");

                    b.HasIndex("OffererPropositionId")
                        .IsUnique();

                    b.ToTable("TradeOffers");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("Balance")
                        .HasColumnType("integer");

                    b.Property<int>("CantAction")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("InGame")
                        .HasColumnType("boolean");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPrisoner")
                        .HasColumnType("boolean");

                    b.Property<int>("Location")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReverseMove")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("GameId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.TurnState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanBuyCell")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanLevelUpCell")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanRollDices")
                        .HasColumnType("boolean");

                    b.Property<int>("CurrentPlayerIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("NeedPay")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("TurnStates");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Room.PlayerInRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("RoomId");

                    b.ToTable("PlayersInRooms");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Room.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("InGame")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxNumberOfPlayers")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.Cells.AmbulanceCell", b =>
                {
                    b.HasBaseType("Monopoly.Core.Models.Abstractions.Classes.Cell");

                    b.HasDiscriminator().HasValue("Ambulance");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.Cells.CasinoCell", b =>
                {
                    b.HasBaseType("Monopoly.Core.Models.Abstractions.Classes.Cell");

                    b.HasDiscriminator().HasValue("Casino");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.Cells.CompanyCell", b =>
                {
                    b.HasBaseType("Monopoly.Core.Models.Abstractions.Classes.Cell");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid>("MonopolyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("Rent")
                        .HasColumnType("integer");

                    b.HasIndex("MonopolyId");

                    b.HasIndex("OwnerId");

                    b.HasDiscriminator().HasValue("CompanyCell");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.Cells.LosingMoneyCell", b =>
                {
                    b.HasBaseType("Monopoly.Core.Models.Abstractions.Classes.Cell");

                    b.Property<int>("Rent")
                        .HasColumnType("integer");

                    b.ToTable("Cells", t =>
                        {
                            t.Property("Rent")
                                .HasColumnName("LosingMoneyCell_Rent");
                        });

                    b.HasDiscriminator().HasValue("LosingMoney");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.Cells.PrisonCell", b =>
                {
                    b.HasBaseType("Monopoly.Core.Models.Abstractions.Classes.Cell");

                    b.HasDiscriminator().HasValue("Prison");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.Cells.ReceiveMoneyCell", b =>
                {
                    b.HasBaseType("Monopoly.Core.Models.Abstractions.Classes.Cell");

                    b.HasDiscriminator().HasValue("ReceiveMoney");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.Cells.RestCell", b =>
                {
                    b.HasBaseType("Monopoly.Core.Models.Abstractions.Classes.Cell");

                    b.HasDiscriminator().HasValue("Rest");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.Cells.ReverceCell", b =>
                {
                    b.HasBaseType("Monopoly.Core.Models.Abstractions.Classes.Cell");

                    b.HasDiscriminator().HasValue("Reverce");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.Cells.StartCell", b =>
                {
                    b.HasBaseType("Monopoly.Core.Models.Abstractions.Classes.Cell");

                    b.HasDiscriminator().HasValue("Start");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Abstractions.Classes.Cell", b =>
                {
                    b.HasOne("Monopoly.Core.Models.Game.GameBoard", "Board")
                        .WithMany("Cells")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.Dice", b =>
                {
                    b.HasOne("Monopoly.Core.Models.Game.Player", "Player")
                        .WithOne("Dices")
                        .HasForeignKey("Monopoly.Core.Models.Game.Dice", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.Game", b =>
                {
                    b.HasOne("Monopoly.Core.Models.Room.Room", "Room")
                        .WithOne("Game")
                        .HasForeignKey("Monopoly.Core.Models.Game.Game", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.GameBoard", b =>
                {
                    b.HasOne("Monopoly.Core.Models.Game.Game", "Game")
                        .WithOne("Board")
                        .HasForeignKey("Monopoly.Core.Models.Game.GameBoard", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.Monopoly", b =>
                {
                    b.HasOne("Monopoly.Core.Models.Game.GameBoard", "Board")
                        .WithMany("Monopolies")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.OfferSystem.TradeOffer", b =>
                {
                    b.HasOne("Monopoly.Core.Models.Game.Game", "Game")
                        .WithOne("CurrentTradeOffer")
                        .HasForeignKey("Monopoly.Core.Models.Game.OfferSystem.TradeOffer", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Monopoly.Core.Models.Game.Player", "Offeree")
                        .WithMany()
                        .HasForeignKey("OffereeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Monopoly.Core.Models.Game.OfferSystem.Proposition", "OffereeProposition")
                        .WithOne()
                        .HasForeignKey("Monopoly.Core.Models.Game.OfferSystem.TradeOffer", "OffereePropositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Monopoly.Core.Models.Game.Player", "Offerer")
                        .WithMany()
                        .HasForeignKey("OffererId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Monopoly.Core.Models.Game.OfferSystem.Proposition", "OffererProposition")
                        .WithOne()
                        .HasForeignKey("Monopoly.Core.Models.Game.OfferSystem.TradeOffer", "OffererPropositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Offeree");

                    b.Navigation("OffereeProposition");

                    b.Navigation("Offerer");

                    b.Navigation("OffererProposition");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.Player", b =>
                {
                    b.HasOne("Monopoly.Core.Models.Account.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Monopoly.Core.Models.Game.Game", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.TurnState", b =>
                {
                    b.HasOne("Monopoly.Core.Models.Game.Game", "Game")
                        .WithOne("TurnState")
                        .HasForeignKey("Monopoly.Core.Models.Game.TurnState", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Room.PlayerInRoom", b =>
                {
                    b.HasOne("Monopoly.Core.Models.Account.Account", "Account")
                        .WithOne()
                        .HasForeignKey("Monopoly.Core.Models.Room.PlayerInRoom", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Monopoly.Core.Models.Room.Room", "Room")
                        .WithMany("Players")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.Cells.CompanyCell", b =>
                {
                    b.HasOne("Monopoly.Core.Models.Game.Monopoly", "Monopoly")
                        .WithMany("Cells")
                        .HasForeignKey("MonopolyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Monopoly.Core.Models.Game.Player", "Owner")
                        .WithMany("OwnedCells")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Monopoly");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.Game", b =>
                {
                    b.Navigation("Board");

                    b.Navigation("CurrentTradeOffer");

                    b.Navigation("Players");

                    b.Navigation("TurnState");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.GameBoard", b =>
                {
                    b.Navigation("Cells");

                    b.Navigation("Monopolies");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.Monopoly", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Game.Player", b =>
                {
                    b.Navigation("Dices");

                    b.Navigation("OwnedCells");
                });

            modelBuilder.Entity("Monopoly.Core.Models.Room.Room", b =>
                {
                    b.Navigation("Game");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
